// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWn5d1aN5_HheryD3izg6lqzW8i2af2xE',
    appId: '1:520812042551:android:334f799c65c2627967e2b2',
    messagingSenderId: '520812042551',
    projectId: 'dyadespace',
    storageBucket: 'dyadespace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvRFrVgHQ5QMUxSzypVdIy-caeC0saro',
    appId: '1:520812042551:ios:9560bc3fb2667cd267e2b2',
    messagingSenderId: '520812042551',
    projectId: 'dyadespace',
    storageBucket: 'dyadespace.firebasestorage.app',
    iosBundleId: 'com.example.dyadespace',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ES1GxRg98rl0jq8tIWOg06HSJhdfC3Q',
    appId: '1:520812042551:web:af68ada00f2b7ff967e2b2',
    messagingSenderId: '520812042551',
    projectId: 'dyadespace',
    authDomain: 'dyadespace.firebaseapp.com',
    storageBucket: 'dyadespace.firebasestorage.app',
    measurementId: 'G-JCG0CWQXFJ',
  );
}
